
from tkinter import *

win = Tk()

def display_input():
   a=var1.get()
   b=var2.get()
   c=var3.get()
   d=var4.get()
   e=var5.get()
   f=var6.get()
   g=var7.get()
   h=var8.get()
   
   print(a,     b,       c,     d,       e,     f,   g,   h)

var1=StringVar()
var2=StringVar()
var3=StringVar()
var4=StringVar()
var5=StringVar()
var6=StringVar()
var7=StringVar()
var8=StringVar()

t1 = Checkbutton(win, text="cancer", variable=var1, onvalue='cancer', offvalue='')
t1.deselect()
t1.grid(row=1,column=0)
t2 = Checkbutton(win, text="high blood pressure", variable=var2, onvalue='high blood pressure', offvalue='')
t2.deselect()
t2.grid(row=2,column=0)
t3 = Checkbutton(win, text="diabetes", variable=var3, onvalue='diabetes', offvalue='')
t3.deselect()
t3.grid(row=3,column=0)
t4 = Checkbutton(win, text="high cholestrol", variable=var4, onvalue='high cholestrol', offvalue='')
t4.deselect()
t4.grid(row=4,column=0)
t5 = Checkbutton(win, text="Asthma or lung disease", variable=var5, onvalue='Asthma or lung disease', offvalue='')
t5.deselect()
t5.grid(row=5,column=0)
t6 = Checkbutton(win, text="Thyroid disease", variable=var6, onvalue='Thyroid disease', offvalue='')
t6.deselect()
t6.grid(row=6,column=0)
t7 = Checkbutton(win, text="Liver disease", variable=var7, onvalue='Liver disease', offvalue='')
t7.deselect()
t7.grid(row=7,column=0)
t8 = Checkbutton(win, text="Dementia", variable=var8, onvalue='Dementia', offvalue='')
t8.deselect()
t8.grid(row=8,column=0)
btn=Buttonbtn=Button(win,text="save data",command=display_input)
btn.grid(row=9,column=0)
win.mainloop()
