from tkinter import*
master=Tk()
def submit():

    import mysql.connector
    mydb=mysql.connector.connect(host='localhost',passwd='kingfisher')
    cursor = mydb.cursor()
    cursor.execute("USE TEST")
    sql='''INSERT INTO MEDICAL_RECORDS(
        ADMN_NUMBER,NAME,AGE,SEX,HEIGHT,WEIGHT,BLOOD_GROUP,
        COVID_VACCINATION,COVID_VACCINATION_DETAILS,PRE_MEDICAL_HISTORY)
        VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)'''
    data=(admn_no.cget('admn_no'),name.cget('name'),age.cget('age'),gender.cget('gender')
          ,height.cget('height'),weight.cget('weight'),
          blood_g.cget('blood_g'),covid.cget('covid'),vaccine.cget('vaccine'),
          history.cget('history'))
    cursor.execute(sql,data)
    mydb.commit()
    '''admn_no_label.destroy()
    name_label.destroy()
    age_label.destroy()
    gender_label.destroy()
    height_label.destroy()
    weight_label.destroy()
    blood_g_label.destroy()
    covid_label.destroy()
    vaccine_label.destroy()
    history_label.destroy()'''
    
admn_no=Entry(master,width=30)
admn_no.grid(row=1,column=1)
name=Entry(master,width=30)
name.grid(row=2,column=1)
age=Entry(master,width=30)
age.grid(row=3,column=1)
gender=Entry(master,width=30)
gender.grid(row=4,column=1)
height=Entry(master,width=30)
height.grid(row=5,column=1)
weight=Entry(master,width=30)
weight.grid(row=6,column=1)
blood=Entry(master,width=30)
blood.grid(row=7,column=1)
covid=Entry(master,width=30)
covid.grid(row=8,column=1)
vaccine=Entry(master,width=30)
vaccine.grid(row=9,column=1)
history=Entry(master,width=30)
history.grid(row=10,column=1)

admn_no=Label(master,text="Enter the patient's admn number")
admn_no.grid(row=1,column=0)
name=Label(master,text="Enter the patient's name")
name.grid(row=2,column=0)
age=Label(master,text="Enter the patient's age")
age.grid(row=3,column=0)
gender=Label(master,text="Enter the patient's gender(m/f)")
gender.grid(row=4,column=0)
height=Label(master,text="Enter the patient's height(in cms)")
height.grid(row=5,column=0)
weight=Label(master,text="Enter the patient's weight(in kg)")
weight.grid(row=6,column=0)
blood_g=Label(master,text="Enter the patient's blood group")
blood_g.grid(row=7,column=0)
covid=Label(master,text="Enter if patient's had covid")
covid.grid(row=8,column=0)
vaccine=Label(master,text="Enter if patient has taken vaccine(and no.of doses)")
vaccine.grid(row=9,column=0)
history=Label(master,text="Enter the patient's pre medical history")
history.grid(row=10,column=0)

submit_button=Button(master,text="Add Record To Database",command=submit)
submit_button.grid(row=11,column=0,columnspan=2,ipadx=150)
mainloop()
