from tkinter import*
window=Tk()
window.title("enter records")
import mysql.connector
mydb=mysql.connector.connect(host='localhost',passwd='kingfisher')
cursor = mydb.cursor()
cursor.execute("use test")
lab1=Label(window,text='admn number').grid(row=1,column=0)
lab2=Label(window,text='name').grid(row=2,column=0)
lab3=Label(window,text='age').grid(row=3,column=0)
lab4=Label(window,text='gender(m/f)').grid(row=4,column=0)
lab5=Label(window,text='height').grid(row=5,column=0)
lab6=Label(window,text='weight').grid(row=6,column=0)
lab7=Label(window,text='blood group').grid(row=7,column=0)
lab8=Label(window,text='if the patient had covid').grid(row=8,column=0)
lab9=Label(window,text='did patient take vaccine(no of doses)').grid(row=9,column=0)
lab10=Label(window,text='pre medical history').grid(row=10,column=0)
ent1=Entry(window)
ent1.grid(row=1,column=1)
ent2=Entry(window)
ent2.grid(row=2,column=1)
ent3=Entry(window)
ent3.grid(row=3,column=1)
ent4=Entry(window)
ent4.grid(row=4,column=1)
ent5=Entry(window)
ent5.grid(row=5,column=1)
ent6=Entry(window)
ent6.grid(row=6,column=1)
ent7=Entry(window)
ent7.grid(row=7,column=1)
ent8=Entry(window)
ent8.grid(row=8,column=1)
ent9=Entry(window)
ent9.grid(row=9,column=1)
ent10=Entry(window)
ent10.grid(row=10,column=1)
def savedata():
    admn_number=ent1.get()
    name=ent2.get()
    age=ent3.get()
    sex=ent4.get()
    height=ent5.get()
    weight=ent6.get()
    blood_group=ent7.get()
    covid_vaccination=ent8.get()
    covid_vaccination_details=ent9.get()
    pre_medical_history=ent10.get()
    cursor.execute('''insert into medical_records
     (admn_number,name,age,sex,height,weight,blood_group,covid_vaccination,
     covid_vaccination_details,pre_medical_history)'''
     "values('"+admn_number+"','"+name+"','"+age+"','"+sex+"','"+height+"','"+weight+"','"+blood_group+"','"+covid_vaccination+"','"+covid_vaccination_details+"','"+pre_medical_history+"')")
    mydb.commit()
    print("record inserted")
    myLabel=Label(window,text='record inserted')
    myLabel.grid(row=12,column=1)
btn=Button(window,text="save data",command=savedata,state=DISABLED)
btn.grid(row=11,column=2)
